### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by benjamincharity** [ocombe/ocModal#15]
Hey @ocombe, just wondering if this project is still being actively maintained? I personally love it since 90% of angular modal libraries depend on Bootstrap which I do not use.

I'm currently using this in several projects but noticed that there hasn't been an update this year. Is `ocModal` still on your radar? I would be willing to help out if needed as I definitely have an interest in seeing this module stay up to date. I just don't want to introduce it to newer projects if it won't be maintained.

Either way, thanks for creating this library to begin with!

**Comment by ocombe** [comment]
Hello !
It isn't widely used, and it has all the features that I need, that's why it hasn't changed.
I still use it at work and we use angular 1.5.x, so it's still working, but we are moving to angular 2, which means that I probably won't use it for long.

If you want to take over, no problem, I can give you push access on the repo, it would be nice to keep this updated !

**Comment by benjamincharity** [comment]
I would definitely help out if you're open to it. Hate for something this useful to get stagnate.  Mainly asking because I've encountered a double digest bug around the `$rootScope.$apply` when modals close (very edge case). I will be forking and (hopefully) fixing for our app and was wondering if a PR would be worthwhile. 

Lord knows how much time this library has probably saved me over the past year or two. Would love to give back any way I can!

Thanks for the quick response!
